name: Deployment Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          mkdir -p C:\Users\USER\.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > C:\Users\USER\.ssh\id_ed_25519
          chmod 600 C:\Users\USER\.ssh\id_ed_25519
          ssh-keyscan -t rsa github.com >> C:\Users\USER\.ssh\known_hosts
          echo "Set up SSH key is completed or nope"
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          ssh -i C:\Users\USER\.ssh\id_ed_25519 -o StrictHostKeyChecking=no user@192.168.1.38  "cd\Users\USER\ && git pull origin main"
          echo "Deployment completed."

          