name: Deployment Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "Set up SSH key is completed"
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          sshpass -p 5fgFGi471b ssh -p 17177 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no mydeploy@www.mydeploymentdomain.com "cd /home/mydeploy && git pull origin main"
          echo "Deployment completed or not."