name: Deployment Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > C:\Users\USER\.ssh\id_ed25519
          ssh-keyscan -t rsa github.com >> C:\Users\USER\.ssh\known_hosts
          echo "Set up SSH key is complete"
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          cd \Users\USER\
          git clone git@github.com:isaranakavisute/html-github-app.git html-github-app1
          cd html-github-app1
          git pull origin main
          echo "Deployment completed"

          